# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    role_hierarchy:
        ROLE_DELIVERY_GUY:   ROLE_USER
        ROLE_MEMBER:         ROLE_DELIVERY_GUY

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
        mysql:
            entity:
                class: AppBundle:User
                property: username

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/overview, roles: ROLE_USER}
        - { path: ^/vendor*, roles: ROLE_MEMBER}
        - { path: ^/browse*, roles: ROLE_MEMBER}
        - { path: ^/cart*, roles: ROLE_MEMBER}
        - { path: ^/chat*, roles: ROLE_MEMBER}
        - { path: ^/product*, roles: ROLE_MEMBER}
        - { path: ^/transaction-history, roles: ROLE_MEMBER}
        - { path: ^/logout, roles: IS_AUTHENTICATED_FULLY}
        - { path: ^/shipments/view, roles: ROLE_DELIVERY_GUY}
        - { path: ^/shipments/delivered/*, roles: ROLE_DELIVERY_GUY}
        - { path: ^/notifications*, roles: ROLE_DELIVERY_GUY}
        - { path: ^/submitMessage/*, roles: ROLE_MEMBER}
        - { path: ^/chatMessages*, roles: ROLE_MEMBER}


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        main:
            anonymous: true
            security: true
            form_login:
                login_path: login
                check_path: login
                default_target_path: /overview
                always_use_default_target_path: true
            logout:
                path: /logout
                target: /
            pattern: ^/
            provider: mysql
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
