<?php

namespace AppBundle\Entity;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function get50LatestMessages() {
        return $this->getEntityManager()
            ->createQuery(
                '
                    SELECT m FROM AppBundle:Message m ORDER BY m.date DESC
                '
            )
            ->setMaxResults(50)
            ->getResult();
    }
}
