<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
* @ORM\Entity(repositoryClass="AppBundle\Entity\OrderRepository")
* @ORM\Table(name="app_orders")
*/
class Order
{
    /**
    * @ORM\Id
    * @ORM\Column(type="integer")
    * @ORM\GeneratedValue(strategy="AUTO")
    */
    private $id;

    /**
    * @ORM\ManyToOne(targetEntity="Product")
    */
    private $product;

    /**
     * @ORM\ManyToOne(targetEntity="Member", inversedBy="orders")
     */
    private $customer;

    /**
    * @ORM\ManyToOne(targetEntity="DeliveryGuy")
    */
    private $deliveryGuy;

    /**
    * @ORM\Column(type="integer")
    * @Assert\NotBlank()
    * @Assert\GreaterThan(value=0)
    */
    private $quantity;

    /**
    * @ORM\Column(type="datetime")
    * @Assert\NotBlank()
    */
    private $transactionDate;

    /**
    * @ORM\Column(type="string")
    * @Assert\NotBlank()
    */
    private $status;


    // methods generated by human hands >_<

    public function getFormattedTransactionDate() {
        return date_format($this->getTransactionDate(), DATE_RFC850);
    }

    public function getTotal() {
        return $this->getQuantity() * $this->getProduct()->getPrice();
    }

    // methods generated by Doctrine ==================

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set quantity
     *
     * @param integer $quantity
     *
     * @return Order
     */
    public function setQuantity($quantity)
    {
        $this->quantity = $quantity;

        return $this;
    }

    /**
     * Get quantity
     *
     * @return integer
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Set transactionDate
     *
     * @param \DateTime $transactionDate
     *
     * @return Order
     */
    public function setTransactionDate($transactionDate)
    {
        $this->transactionDate = $transactionDate;

        return $this;
    }

    /**
     * Get transactionDate
     *
     * @return \DateTime
     */
    public function getTransactionDate()
    {
        return $this->transactionDate;
    }

    /**
     * Set status
     *
     * @param string $status
     *
     * @return Order
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set product
     *
     * @param \AppBundle\Entity\Product $product
     *
     * @return Order
     */
    public function setProduct(\AppBundle\Entity\Product $product = null)
    {
        $this->product = $product;

        return $this;
    }

    /**
     * Get product
     *
     * @return \AppBundle\Entity\Product
     */
    public function getProduct()
    {
        return $this->product;
    }

    /**
     * Set customer
     *
     * @param \AppBundle\Entity\Member $customer
     *
     * @return Order
     */
    public function setCustomer(\AppBundle\Entity\Member $customer = null)
    {
        $this->customer = $customer;

        return $this;
    }

    /**
     * Get customer
     *
     * @return \AppBundle\Entity\Member
     */
    public function getCustomer()
    {
        return $this->customer;
    }

    /**
     * Get store
     *
     * @return \AppBundle\Entity\Store
     */
    public function getStore()
    {
        return $this->getProduct()->getStore();
    }

    /**
     * Set deliveryGuy
     *
     * @param \AppBundle\Entity\DeliveryGuy $deliveryGuy
     *
     * @return Order
     */
    public function setDeliveryGuy(\AppBundle\Entity\DeliveryGuy $deliveryGuy = null)
    {
        $this->deliveryGuy = $deliveryGuy;

        return $this;
    }

    /**
     * Get deliveryGuy
     *
     * @return \AppBundle\Entity\DeliveryGuy
     */
    public function getDeliveryGuy()
    {
        return $this->deliveryGuy;
    }
}
