<?php

namespace AppBundle\Entity;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllPendingOrdersOfAProduct($product)
    {
        return $this->getEntityManager()
            ->createQuery(
                '
                    SELECT o FROM AppBundle:Order o WHERE o.product=:product AND o.status=\'CHECKED-OUT\'
                '
            )
            ->setParameter('product', $product)
            ->getResult();
    }

    public function findOneOrderThatExistsInCart($customer, $product) {
        return $this->getEntityManager()
            ->createQuery(
                '
                    SELECT c FROM AppBundle:Order c WHERE c.customer=:customer AND c.product=:product AND c.status=\'IN-CART\'
                '
            )
            ->setParameter('customer', $customer)
            ->setParameter('product', $product)
            ->getSingleResult();
    }

    public function findAllPendingOrdersOfMemberByStore($store) {
        return $this->getEntityManager()
            ->createQuery(
                '
                    SELECT o FROM AppBundle:Order o WHERE o.store=:store AND o.status=\'CHECKED-OUT\' ORDER BY o.transactionDate ASC, o.id ASC
                '
            )
            ->setParameter('store', $store)
            ->getResult();
    }
}
