<?php

namespace AppBundle\Entity;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllActiveProductsInASpecificStore($store)
    {
        return $this->getEntityManager()
            ->createQuery(
                '
                    SELECT p FROM AppBundle:Product p WHERE p.store=:store AND p.isActive=true
                '
            )
            ->setParameter('store', $store)
            ->getResult();
    }
}
